# Generated by Django 2.1 on 2019-02-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
