# Generated by Django 2.1 on 2019-02-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190224_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bigoraphy',
            new_name='biography',
        ),
    ]
